# Configuración del proyecto en SonarQube
sonar.host.url=https://sonarqube.ingsoftware.lat/
sonar.login=students
sonar.password=Ut3c2026GG++

# Identificadores obligatorios del proyecto
sonar.projectKey=Gracia_Mendoza_t1
sonar.projectName=Gracia_Mendoza_t1
sonar.projectVersion=1.0.0

# Directorios de código fuente (multi-módulo)
sonar.sources=shared-events,restaurant-service,reward-service,notification-service
sonar.sourceEncoding=UTF-8

# Rutas de binarios compilados
sonar.java.binaries=shared-events/target/classes,restaurant-service/target/classes,reward-service/target/classes,notification-service/target/classes
