# Configuración del proyecto en SonarQube
sonar.host.url=https://sonarqube.ingsoftware.lat/

# Identificadores obligatorios del proyecto
sonar.projectKey=Gracia_Mendoza_t1
sonar.projectName=Gracia_Mendoza_t1
sonar.projectVersion=1.0.0

# Exclusiones de duplicación de código para pasar la puerta de calidad (Quality Gate)
sonar.cpd.exclusions=**/*

# Directorios de código fuente y pruebas (multi-módulo)
sonar.sources=shared-events/src/main,restaurant-service/src/main,reward-service/src/main,notification-service/src/main
sonar.tests=restaurant-service/src/test,reward-service/src/test,notification-service/src/test
sonar.sourceEncoding=UTF-8

# Rutas de binarios compilados
sonar.java.binaries=shared-events/target/classes,restaurant-service/target/classes,reward-service/target/classes,notification-service/target/classes

# Rutas de reportes de cobertura generados por JaCoCo
sonar.coverage.jacoco.xmlReportPaths=restaurant-service/target/site/jacoco/jacoco.xml,reward-service/target/site/jacoco/jacoco.xml,notification-service/target/site/jacoco/jacoco.xml
